USE master
GO

CREATE DATABASE LocacaoVeiculo
GO

USE LocacaoVeiculo
GO

-- TABLES --

CREATE TABLE tbEndereco 
(
	END_CODIGO INT NOT NULL IDENTITY(1,1),
	END_CEP VARCHAR (9) NOT NULL,
	END_RUA VARCHAR(50) NOT NULL,
	END_BAIRRO VARCHAR(30) NOT NULL,
	END_NUMERO INT NOT NULL,
	END_COMPLEMENTO VARCHAR(20)	
)
GO

CREATE TABLE tbCliente
(
	END_CODIGO INT NOT NULL,
	CLN_CODIGO INT NOT NULL IDENTITY(1,1),
	CLN_NOME VARCHAR(50) NOT NULL,
	CLN_CPF VARCHAR(14) NOT NULL,
	CLN_EMAIL VARCHAR(30) NOT NULL,
	CLN_TELEFONE VARCHAR(14) NOT NULL,
	CLN_DATACADASTRO DATE NOT NULL
)
GO

CREATE TABLE tbUsuario
(
	USR_CODIGO INT NOT NULL IDENTITY(1,1),
	USR_NOME VARCHAR(50) NOT NULL,
	USR_CPF VARCHAR(14) NOT NULL,
	USR_EMAIL VARCHAR(30) NOT NULL,
	USR_CARGO VARCHAR(8) NOT NULL,
	USR_LOGIN VARCHAR(15) NOT NULL,
    USR_SENHA VARCHAR(15) NOT NULL
)
GO

CREATE TABLE tbMarca
(
	MRC_CODIGO INT NOT NULL IDENTITY(1,1),
	MRC_NOME VARCHAR(20) NOT NULL
)
GO

CREATE TABLE tbVeiculo
(
	MRC_CODIGO INT NOT NULL,
	VCL_CODIGO INT NOT NULL IDENTITY(1,1),
	VCL_NOME VARCHAR(30) NOT NULL,
	VCL_DATACADASTRO DATE NOT NULL,
	VCL_ANO INT NOT NULL,
	VCL_VALORCOMPRA DECIMAL(8,2) NOT NULL,
	VCL_PERCENTLOCACAO DECIMAL(5,4) NOT NULL
)
GO


CREATE TABLE tbManutencao
(
	VCL_CODIGO INT NOT NULL,
	MTN_CODIGO INT NOT NULL IDENTITY(1,1),
	MTN_DATACADASTRO DATE NOT NULL,
	MTN_DESCRICAO VARCHAR(50) NOT NULL,
	MTN_VALOR DECIMAL(5,2) NOT NULL,
	MTN_KMRODADOS DECIMAL(5,2) NOT NULL	
)
GO

CREATE TABLE tbLocacao
(
	USR_CODIGO INT NOT NULL,
    CLN_CODIGO INT NOT NULL,
	VCL_CODIGO INT NOT NULL,
	LCA_CODIGO INT NOT NULL IDENTITY(1,1),
	LCA_DATAINICIO DATE NOT NULL,
    LCA_DATAFIM DATE NOT NULL,
	LCA_QTDDIAS INT NOT NULL,
    LCA_VALORTOTAL DECIMAL(8,2) NOT NULL,
    LCA_PAGAMENTO VARCHAR(10) NOT NULL,
    LCA_STATUS VARCHAR(10) NOT NULL
)
GO

-- PRIMARY KEYS --

ALTER TABLE tbEndereco
ADD CONSTRAINT PK_Endereco
PRIMARY KEY (END_CODIGO)
GO

ALTER TABLE tbCliente
ADD CONSTRAINT PK_Cliente
PRIMARY KEY (CLN_CODIGO)
GO

ALTER TABLE tbUsuario
ADD CONSTRAINT PK_Usuario
PRIMARY KEY (USR_CODIGO)
GO

ALTER TABLE tbMarca
ADD CONSTRAINT PK_Marca
PRIMARY KEY (MRC_CODIGO)
GO

ALTER TABLE tbVeiculo
ADD CONSTRAINT PK_Veiculo
PRIMARY KEY (VCL_CODIGO)
GO

ALTER TABLE tbLocacao
ADD CONSTRAINT PK_Locacao
PRIMARY KEY (LCA_CODIGO)
GO

ALTER TABLE tbManutencao
ADD CONSTRAINT PK_Manutencao
PRIMARY KEY (MTN_CODIGO)
GO

-- FOREIGN KEYS --

ALTER TABLE tbCliente
ADD CONSTRAINT FK_Endereco
FOREIGN KEY (END_CODIGO)
REFERENCES tbEndereco (END_CODIGO)
GO

ALTER TABLE tbVeiculo
ADD CONSTRAINT FK_Marca
FOREIGN KEY (MRC_CODIGO)
REFERENCES tbMarca (MRC_CODIGO)
GO


ALTER TABLE tbLocacao
ADD CONSTRAINT FK_Usuario
FOREIGN KEY (USR_CODIGO)
REFERENCES tbUsuario (USR_CODIGO)
GO

ALTER TABLE tbLocacao
ADD CONSTRAINT FK_Cliente
FOREIGN KEY (CLN_CODIGO)
REFERENCES tbCliente (CLN_CODIGO)
GO

ALTER TABLE tbLocacao
ADD CONSTRAINT FK_Veiculo_Locacao
FOREIGN KEY (VCL_CODIGO)
REFERENCES tbVeiculo(VCL_CODIGO)
GO

ALTER TABLE tbManutencao
ADD CONSTRAINT FK_Veiculo_Manutencao
FOREIGN KEY (VCL_CODIGO)
REFERENCES tbVeiculo(VCL_CODIGO)
GO

-- CONSTRAINTS --

ALTER TABLE tbCliente ADD CONSTRAINT UniqueEndereco UNIQUE(END_CODIGO)
GO

-- USUÁRIO ADMINISTRADOR PADRÃO --
INSERT INTO tbUsuario (USR_NOME,USR_CPF,USR_EMAIL,USR_CARGO,USR_LOGIN,USR_SENHA) VALUES ('Administrador','000.000.000-00','administrador@adm.com','GERENTE','administrador','1234')
GO
